sudo: required

services: docker

before_install:
  - docker-compose up --build -d

script:
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:create
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:migrateã€€
  - docker-compose exec --env 'RAILS_ENV=test' web rails test